//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstApproachCRUD_OprationMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENTSEF
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string GENDER { get; set; }
        public int AGE { get; set; }
        public int STANDARD { get; set; }
    }
}
